import { NextRequest, NextResponse } from 'next/server';
import AWS from 'aws-sdk';
import { createClient } from '@supabase/supabase-js';
import { canAccessLectureRecordings } from '@/lib/access-control';
import crypto from 'crypto';

export const dynamic = 'force-dynamic';

// AWS S3
const s3 = new AWS.S3({
  accessKeyId: process.env.AWS_ACCESS_KEY_ID,
  secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
  region: process.env.AWS_REGION,
});

const VIDEO_BUCKET = process.env.AWS_S3_BUCKET_LESSON_HLS!;

// Supabase (service role)
const supabaseAdmin = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

const STREAM_SECRET = process.env.LECTURE_STREAM_SECRET;

interface TokenPayload {
  sub: string;
  key: string;
  courseId: string;
  exp: number;
}

function verifyAccessToken(token: string): TokenPayload | null {
  if (!STREAM_SECRET) return null;
  const parts = token.split('.');
  if (parts.length !== 2) return null;
  const [base, sig] = parts;
  const expected = crypto
    .createHmac('sha256', STREAM_SECRET)
    .update(base)
    .digest('base64url');
  if (!crypto.timingSafeEqual(Buffer.from(sig), Buffer.from(expected))) {
    return null;
  }
  try {
    const payload = JSON.parse(
      Buffer.from(base, 'base64url').toString('utf8')
    ) as TokenPayload;
    const now = Math.floor(Date.now() / 1000);
    if (payload.exp && payload.exp < now) {
      return null;
    }
    return payload;
  } catch {
    return null;
  }
}

export async function GET(request: NextRequest) {
  try {
    const url = new URL(request.url);
    const key = url.searchParams.get('key');
    const authHeader = request.headers.get('authorization');
    const tokenFromQuery = url.searchParams.get('token'); // legacy, will be ignored for auth
    const accessToken = url.searchParams.get('accessToken');
    const secFetchDest = request.headers.get('sec-fetch-dest') || '';
    const range = request.headers.get('range') || undefined;

    if (!key) {
      return new NextResponse('Missing key', { status: 400 });
    }

    // Prevent opening the stream URL directly in a browser tab (which shows
    // the default video UI with easy download options). When the URL is
    // loaded via a <video> element, modern browsers send sec-fetch-dest=video;
    // when the user pastes the URL in the address bar or opens it as a page,
    // sec-fetch-dest=document.
    if (secFetchDest === 'document') {
      return new NextResponse('Direct access to video URL is not allowed', {
        status: 403,
      });
    }

    let userId: string | null = null;
    let courseIdFromToken: string | null = null;
    let requireAccessCheck = true;

    // Prefer standard Authorization header (e.g. for direct authorized clients)
    if (authHeader) {
      const bearer = authHeader.replace('Bearer ', '');
      const {
        data: { user },
        error: userError,
      } = await supabaseAdmin.auth.getUser(bearer);
      if (userError || !user) {
        return new NextResponse('Unauthorized', { status: 401 });
      }
      userId = user.id;
    } else if (accessToken) {
      // Fallback: signed, short‑lived access token generated by /access-token route
      const payload = verifyAccessToken(accessToken);
      if (!payload) {
        return new NextResponse('Invalid or expired token', { status: 401 });
      }
      if (payload.key !== key) {
        return new NextResponse('Invalid token for this resource', {
          status: 403,
        });
      }
      userId = payload.sub;
      courseIdFromToken = payload.courseId;
      // We already did all access checks when issuing this token, so we can
      // skip hitting Supabase again here for faster startup.
      requireAccessCheck = false;
    } else {
      return new NextResponse('Authorization required', { status: 401 });
    }

    // Find the recording by key
    const { data: recording } = await supabaseAdmin
      .from('lecture_recordings')
      .select('id, course_id, teacher_id, is_published')
      .eq('video_key', key)
      .maybeSingle();

    if (!recording) {
      return new NextResponse('Recording not found', { status: 404 });
    }

    // If we came from a signed token, ensure course id matches payload
    if (courseIdFromToken && courseIdFromToken !== recording.course_id) {
      return new NextResponse('Invalid token for this course', { status: 403 });
    }

    if (requireAccessCheck) {
      // Get user role
      const { data: userProfile } = await supabaseAdmin
        .from('users')
        .select('role')
        .eq('id', userId!)
        .single();

      const role = userProfile?.role;
      const isAdmin = role === 'admin' || role === 'superadmin';

      // Permission checks (for direct bearer auth requests)
      if (role === 'student') {
        // Check if recording is published
        if (!recording.is_published) {
          return new NextResponse('Recording not published', { status: 403 });
        }

        // Check subscription or demo access
        const accessResult = await canAccessLectureRecordings(
          userId!,
          recording.course_id
        );
        
        if (!accessResult.hasAccess) {
          return new NextResponse(
            JSON.stringify({ 
              error: 'Access denied', 
              message: accessResult.message,
              requiresSubscription: true 
            }), 
            { 
              status: 403,
              headers: { 'Content-Type': 'application/json' }
            }
          );
        }
      } else if (role === 'teacher') {
        const { data: teacherCourse } = await supabaseAdmin
          .from('teacher_courses')
          .select('course_id')
          .eq('teacher_id', userId!)
          .eq('course_id', recording.course_id)
          .maybeSingle();
        if (!teacherCourse && !isAdmin && userId !== recording.teacher_id) {
          return new NextResponse('Forbidden', { status: 403 });
        }
      } else if (!isAdmin) {
        // Unknown role
        return new NextResponse('Forbidden', { status: 403 });
      }
    }

    // HEAD to get metadata
    const head = await s3.headObject({ Bucket: VIDEO_BUCKET, Key: key }).promise();
    const totalLength = Number(head.ContentLength || 0);
    const contentType = head.ContentType || 'video/mp4';

    let start = 0;
    let end = totalLength ? totalLength - 1 : undefined as unknown as number;
    let status = 200;

    const headers: Record<string, string> = {
      'Content-Type': contentType,
      'Accept-Ranges': 'bytes',
      'Cache-Control': 'no-store',
      'Content-Disposition': 'inline',
      'X-Content-Type-Options': 'nosniff',
    };

    if (range && totalLength) {
      const match = /bytes=(\d+)-(\d*)/.exec(range);
      if (match) {
        start = parseInt(match[1], 10);
        end = match[2] ? parseInt(match[2], 10) : totalLength - 1;
        if (isNaN(start) || isNaN(end) || start > end || end >= totalLength) {
          return new NextResponse('Invalid Range', { status: 416 });
        }
        status = 206;
        headers['Content-Range'] = `bytes ${start}-${end}/${totalLength}`;
        headers['Content-Length'] = String(end - start + 1);
      }
    } else if (totalLength) {
      headers['Content-Length'] = String(totalLength);
    }

    const params: AWS.S3.GetObjectRequest = { Bucket: VIDEO_BUCKET, Key: key };
    if (status === 206) {
      params.Range = `bytes=${start}-${end}`;
    }

    const s3Object = s3.getObject(params);
    const nodeStream = s3Object.createReadStream();

    const readable = new ReadableStream({
      start(controller) {
        nodeStream.on('data', (chunk) => controller.enqueue(chunk));
        nodeStream.on('end', () => controller.close());
        nodeStream.on('error', (err) => controller.error(err));
      },
      cancel() {
        try { 
          nodeStream.destroy(); 
        } catch (destroyError) {
          console.error('Error destroying stream:', destroyError);
        }
      }
    });

    return new NextResponse(readable as any, { status, headers });
  } catch (error) {
    console.error('Stream error:', error);
    return new NextResponse('Failed to stream video', { status: 500 });
  }
}


